#!/bin/bash

folder="$1"
if [ ! -d "$folder" ]; then
	echo 'Primul argument trebuie sa fie un folder.'
	exit 1
fi

contents="$( ls $1 )"
while true; do
	sleep 1
	
	clear
	new_contents="$( ls $1 )"
	if [ "$new_contents" != "$contents" ]; then
		echo 'S-a schimbat!!!'
	else
		echo 'Nu s-a schimbat...'
	fi
	contents="$new_contents"
done
