#!/bin/bash

(
	IFS=$'\n'

	words=''
	sep=''
	for word in "$@"; do
		words="$words$sep$word"
		sep=$'\n'
	done

	while [ -n "$words" ]; do
		read file
		new_words=''
		sep=''
		for word in $( echo "$words" ); do
			if grep -q "\b$word\b" "$file"; then
				echo "Found $word in $file."
			else
				new_words="$new_words$sep$word"
				sep=$'\n'
			fi
		done
		words="$new_words"
	done
)
