#!/bin/sh

if [ $# -lt 1 ]; then
	echo 'Insufficient arguments.'
	exit 1
fi

if [ ! -d "$1" ]; then
	echo 'Error: "'"$1"'" is not a directory.'
	exit 1
fi

{ for file in $( ls "$1" | grep '^.*\.c$' ); do
	cat "$1/$file" | grep -vc '^\s*$'
done } | awk 'BEGIN{lines=0}{lines += $1}END{print lines}'
