#!/bin/bash

if [ -n "$1" ]; then
	folder="$1"
else
	folder='.'
fi

(
	IFS=$'\n'
	for file in $( find "$folder" -type f ); do
		if [ "$(file -b $file)" = 'ASCII text' ]; then
			printf "$file\n"
			stat --printf='\tmarime: %s\n\tpermisiuni: %A\n' "$file"
			printf "\tlinii unice: $( sort $file | uniq | wc -l )\n"
		fi
	done
)
