#!/bin/bash

if [ $# -lt 1 ]; then
	echo 'Insufficient arguments.'
	exit 1
fi

if [ ! -d "$1" ]; then
	echo 'Error: "'"$1"'" is not a directory.'
	exit 1
fi

(
	IFS=$'\n'
	lines=0
	for file in $( find "$1" -type f -name '*.c' ); do
		lines=$(( $lines + $( grep -vc '^\s*$' "$file" ) ))
	done
	echo "$lines"
)
