#!/bin/bash

file="$1"
if [ ! -f "$file" ]; then
	echo 'Primul argument trebuie sa fie un fisier.'
	exit 1
fi

echo -n > emails.txt
(
	IFS=$'\n'
	sep=''
	for name in $( cat "$file" ); do
		echo -n "$sep$name@scs.ubbcluj.ro" >> emails.txt
		sep=', '
	done
	echo >> emails.txt
)
