#!/bin/bash

(
	IFS=$'\n'
	for a in $@; do
		answer='altceva'
		if [ -f "$a" ]; then
			answer='un fisier'
		elif [ -d "$a" ]; then
			answer='un director'
		elif echo "$a" | grep -E --quiet '^[0-9]+$'; then
			answer='un numar'
		fi
		echo "$a este $answer"
	done
)
