#!/bin/bash

d="$1"
if [ ! -d "$d" ]; then
	echo 'Primul argument trebuie sa fie director.'
	exit 1
fi

(
	IFS=$'\n'
	size='0'
	for f in $( ls "$d" ); do
		if [ -f "$f" ]; then
			size=$(( "$size" + $( stat -c'%s' "$f" ) ))
		fi
		echo "$f"
	done
	echo "$size"
)
