#!/bin/bash

read file
while [ "$file" != 'stop' ]; do
	test -f "$file" || echo what
	if [ -f "$file" -a "$( file -b $file )" = 'ASCII text' ]; then
		words=$( head -n 1 "$file" | wc -w )
		echo "Fisierul $file are $words cuvinte pe prima linie."
	fi
	read file
done
