#!/bin/bash

while [ "$#" -ge 2 ]; do
	file="$1"
	word="$2"
	shift 2
	if [ -f "$file" ]; then
		if cat "$file" | tr '\n' ' ' | grep -q ".*\b$word\b.*\b$word\b.*\b$word\b.*"; then
			echo 'da'
		else
			echo 'nu'
		fi
	fi
	echo "$file"
done
