CC=gcc
CFLAGS=-Wall -g

all: fork_1 fork_2 fork_3 fork_4 fork_5 fork_6 fork_7 fork_8

fork_1: fork_1.c

fork_2: fork_2.c

fork_3: fork_3.c

fork_4: fork_4.c

fork_5: fork_5.c

fork_6: fork_6.c

fork_7: fork_7.c

fork_8: fork_8.c


