#!/bin/sh
u=$( echo $@ | tr ' ' '|' )

clear
while true; do
	p=$( ps -ef         \
		| cut -d' ' -f1 \
		| sort          \
		| uniq -c       \
		| sort -nr      )

	if [ "$u" ]; then
		echo "$p" | awk '$2 ~ /^('"$u"')$/ { print $0 }'
	else
		echo "$p"
	fi

	sleep 1
	clear
done
